### ISSUE TITLE
Could not get it working

### ISSUE THREAD

**Issue by servimo** [pachanka/moc-scrobbler#2]
Could not get it working:

moc-scrobbler --artist="Piero Umiliani" --track="Mah Nà Mah Nà"
Submitting Piero Umiliani - Mah Nà Mah Nà
Using provided API credentials.
Got 2792eb59e0cae0aa6824a4ee7a652824 
Scrobbling...
Error:
<?xml version="1.0" encoding="utf-8"?> <lfm status="failed">   <error code="13">Invalid method signature supplied</error> </lfm>
Aborting.

**Comment by pachanka** [comment]
Hello @servimo sorry for the late reply, vacations were in order.

You are right, it seems that the current build is broken and sending out incorrect signatures. I'll take a look and post back asap.

Thanks for reaching out to notify me about this.

**Comment by servimo** [comment]
It is working again. 
I created a new SESSION_KEY, API_KEY,  API_SEC
 on page of last.fm for moc

**Comment by pachanka** [comment]
Glad you got it working.

Most of the time removing the `~/.config/moc-scrobbler` directory and then running

```
$ moc-scrobbler --connect
```

Will fix any trouble by replacing the config file. But adding your own `API_SEC` key to the configuration file is far better because it will not need to call pachanka.org to sign the submission on every track before sending it to last.fm.
